import type { Level } from '../types'

const level: Level = {
  id: 'amateur',
  title: 'CSS, semantics and forms',
  summary:
    'Take control of how your pages look, structure them the way real sites do, and collect information from visitors with forms.',
  outcomes: [
    'Attach CSS three ways and know which to use',
    'Target elements with selectors, and resolve conflicts',
    'Control colour, type and spacing',
    'Reason about the box model and display types',
    'Use semantic layout elements instead of endless divs',
    'Build accessible forms and tables',
  ],
  steps: [
    {
      id: 'html-a-01',
      title: 'Adding CSS to a page',
      read: `**CSS** — Cascading Style Sheets — controls how HTML looks. A rule has two parts:

\`\`\`css
h1 {
  color: navy;
  font-size: 32px;
}
\`\`\`

- \`h1\` is the **selector**: which elements this applies to
- inside the braces are **declarations**, each \`property: value;\`
- the semicolon ends each declaration. Missing one breaks that declaration *and* the next.

## Three ways to attach it

1. **Inline** — \`<p style="color: red;">\`. Applies to one element. Hard to maintain, impossible to reuse. Avoid except for values generated by a program.
2. **Internal** — a \`<style>\` block in \`<head>\`. Fine for a single page or a quick experiment.
3. **External** — a separate \`.css\` file, linked from \`<head>\`:

\`\`\`html
<link rel="stylesheet" href="styles.css">
\`\`\`

**External is the right answer** for anything real. One file styles your whole site, the browser caches it, and your HTML stays about content.

## Comments

\`/* like this */\` — note that \`//\` is **not** a CSS comment.`,
      sample: {
        lang: 'html',
        caption: 'All three methods, shown together for comparison',
        code: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Styling</title>

    <!-- 3. external: the one to use -->
    <link rel="stylesheet" href="styles.css">

    <!-- 2. internal -->
    <style>
      /* every h1 on this page */
      h1 {
        color: navy;
        font-size: 32px;
      }
      p {
        line-height: 1.6;
        color: #333333;
      }
    </style>
  </head>
  <body>
    <h1>Styled heading</h1>
    <p>A normal paragraph.</p>

    <!-- 1. inline: avoid -->
    <p style="color: crimson; font-weight: bold;">A shouty paragraph.</p>
  </body>
</html>`,
        output: `Styled heading      (navy, 32px)
A normal paragraph. (dark grey, comfortable line spacing)
A shouty paragraph. (crimson, bold)`,
      },
      question: {
        kind: 'mcq',
        prompt: 'Which line links an external stylesheet correctly?',
        options: [
          '`<style src="styles.css">`',
          '`<link rel="stylesheet" href="styles.css">`',
          '`<css href="styles.css">`',
          '`<script src="styles.css">`',
        ],
        answer: 1,
        explain:
          '`<link>` with `rel="stylesheet"` and `href` is the one and only correct form, and it belongs in `<head>`. `<style>` holds CSS written inline in the document; `<script>` is for JavaScript.',
        hint: 'Stylesheets use `href`, like links do.',
      },
    },

    {
      id: 'html-a-02',
      title: 'Selectors and the cascade',
      read: `## The selectors you need first

- \`p\` — every \`<p>\` element
- \`.card\` — every element with \`class="card"\`
- \`#header\` — the element with \`id="header"\`
- \`*\` — everything
- \`h1, h2, h3\` — a **group**: all three
- \`.card p\` — a **descendant**: any \`<p>\` anywhere inside \`.card\`
- \`.card > p\` — a **direct child** only
- \`a:hover\` — a **pseudo-class**: a link being hovered
- \`input[type="email"]\` — an **attribute** selector

## When two rules conflict

CSS resolves it in this order:

1. **Specificity** — how precisely the selector targets the element. Count \`(ids, classes, elements)\`: \`#nav\` = (1,0,0) beats \`.menu.dark\` = (0,2,0) beats \`ul li\` = (0,0,2). Higher wins, compared left to right.
2. **Source order** — with equal specificity, the later rule wins.

That is the "cascading" in the name.

## !important

\`color: red !important;\` overrides everything. It is almost always the wrong fix — it starts an escalation where the next override needs \`!important\` too. Fix the specificity instead.

> Practical advice: style with **classes**. Keep specificity flat and predictable, and you will almost never need to think about this.`,
      sample: {
        lang: 'css',
        caption: 'Specificity in action — read the comments for who wins',
        code: `/* (0,0,1) — every paragraph */
p { color: grey; }

/* (0,1,0) — beats the above for .intro paragraphs */
.intro { color: black; }

/* (0,1,1) — beats .intro for paragraphs inside .card */
.card p { color: navy; }

/* (1,0,0) — beats everything above */
#lead { color: crimson; }

/* group */
h1, h2, h3 { font-family: Georgia, serif; }

/* direct child only */
.menu > li { list-style: none; }

/* pseudo-classes */
a:hover { text-decoration: underline; }
a:visited { color: purple; }
li:first-child { font-weight: bold; }
li:nth-child(odd) { background: #f4f4f4; }

/* attribute selector */
input[type="email"] { border-color: steelblue; }`,
        output: `<p>            -> grey
<p class="intro"> -> black
<div class="card"><p> -> navy
<p id="lead" class="intro"> -> crimson`,
      },
      question: {
        kind: 'mcq',
        prompt:
          'Both rules match the same element. Which colour wins?\n\n```css\n.button { color: blue; }\n#submit { color: green; }\n```',
        options: ['blue, because it comes first', 'green, because an id beats a class', 'blue, because classes are more specific', 'Neither — they cancel out'],
        answer: 1,
        explain:
          'Specificity is checked before source order, and one id (1,0,0) outranks any number of classes (0,n,0). This is exactly why over-using ids for styling makes a stylesheet hard to override later.',
        hint: 'Which comes first, specificity or source order?',
      },
    },

    {
      id: 'html-a-03',
      title: 'Colour, text and fonts',
      read: `## Colour

- Named: \`red\`, \`navy\`, \`rebeccapurple\` (148 of them)
- Hex: \`#ff0000\`, shortened to \`#f00\`. Pairs are red, green, blue, each \`00\`–\`ff\`.
- \`rgb(255 0 0)\`, and with transparency \`rgb(255 0 0 / 50%)\`
- \`hsl(0 100% 50%)\` — hue (0–360), saturation, lightness. Much easier to build a palette with: keep the hue, vary the lightness.

\`color\` sets text; \`background-color\` sets the area behind it.

## Text properties

- \`font-size\` — use \`rem\` (relative to the root size) rather than \`px\` so it respects the user's settings
- \`font-weight\` — \`400\` normal, \`700\` bold
- \`line-height\` — **1.5 or 1.6 unitless** for body text. The single biggest readability win available.
- \`text-align\`, \`letter-spacing\`, \`text-transform\`, \`text-decoration\`

## Fonts

\`font-family\` takes a **stack**: the browser tries each in turn.

\`\`\`css
font-family: "Helvetica Neue", Arial, sans-serif;
\`\`\`

Always end with a generic family (\`sans-serif\`, \`serif\`, \`monospace\`). The modern **system font stack** uses whatever the OS provides — zero download, instantly familiar, and it never causes a flash of unstyled text.`,
      sample: {
        lang: 'css',
        caption: 'A readable typographic base for any page',
        code: `:root {
  --ink: hsl(222 25% 18%);
  --muted: hsl(222 12% 45%);
  --brand: hsl(205 90% 45%);
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
               Helvetica, Arial, sans-serif;
  font-size: 1rem;
  line-height: 1.6;
  color: var(--ink);
  background-color: #fdfdfd;
  max-width: 65ch;
  margin: 0 auto;
  padding: 2rem 1rem;
}

h1 {
  font-size: 2.25rem;
  line-height: 1.2;
  letter-spacing: -0.02em;
}

.muted { color: var(--muted); }

a {
  color: var(--brand);
  text-decoration-thickness: 2px;
  text-underline-offset: 2px;
}

.badge {
  background: var(--brand);
  color: white;
  text-transform: uppercase;
  font-size: 0.75rem;
  letter-spacing: 0.08em;
  padding: 0.2rem 0.6rem;
  border-radius: 999px;
}`,
        output: `A comfortable page: dark-blue text on near-white, 65 characters per line,
1.6 line spacing, a tight large heading, and a small rounded uppercase badge.`,
      },
      question: {
        kind: 'mcq',
        prompt: 'Why is `line-height: 1.6` (no unit) usually better than `line-height: 24px`?',
        options: [
          'It is shorter to type',
          'It scales with each element’s own font size, so headings and body text both get sensible spacing',
          'Pixels are not supported for line-height',
          'It renders faster',
        ],
        answer: 1,
        explain:
          'A unitless line-height is a multiplier applied per element. A fixed `24px` inherited by a 40px heading would cram the lines together. Unitless is one of the few CSS values that behaves correctly everywhere by default.',
        hint: 'What happens to an inherited fixed value on a much bigger heading?',
      },
    },

    {
      id: 'html-a-04',
      title: 'The box model',
      read: `Every element is a rectangular box with four layers, from the inside out:

1. **content** — the text or image itself
2. **padding** — space *inside* the box, between content and border. Takes the background colour.
3. **border** — the line around it
4. **margin** — space *outside*, pushing other elements away. Always transparent.

## The sizing trap

By default, \`width: 300px\` sets the **content** width. Add \`20px\` padding and a \`2px\` border and the box occupies 344px, not 300. This surprises everyone.

The fix, which essentially every real stylesheet starts with:

\`\`\`css
*, *::before, *::after {
  box-sizing: border-box;
}
\`\`\`

Now \`width\` means the **whole visible box**, padding and border included, and layouts behave the way you expect.

## Shorthand

\`padding: 10px\` (all sides) · \`10px 20px\` (vertical, horizontal) · \`10px 20px 30px 40px\` (top, right, bottom, left — clockwise from the top).

## Margin collapse

Vertical margins between siblings **collapse** into the larger of the two, not the sum. 20px below one paragraph and 30px above the next gives 30px, not 50. Horizontal margins never collapse. This only happens with margins, which is one reason many people reach for padding or \`gap\` instead.

\`margin: 0 auto\` centres a block that has a width.`,
      sample: {
        lang: 'css',
        caption: 'The reset every stylesheet should open with, then a typical card',
        code: `*, *::before, *::after {
  box-sizing: border-box;
}

body {
  margin: 0;
}

.card {
  width: 300px;          /* the whole box is 300px wide */
  padding: 20px;
  border: 2px solid #ddd;
  border-radius: 12px;
  margin: 0 auto 24px;   /* top:0  left/right:auto  bottom:24px */
  background: white;
  box-shadow: 0 2px 8px rgb(0 0 0 / 8%);
}

.card h3 {
  margin-top: 0;         /* stops the heading's margin escaping the card */
}

.spaced > * + * {
  margin-top: 1rem;      /* space between children, but not above the first */
}`,
        output: `Without border-box: a "300px" card actually occupies 344px.
With border-box:    it occupies exactly 300px, and centring works predictably.`,
      },
      question: {
        kind: 'fill',
        prompt:
          'With the default `box-sizing`, how many pixels wide is this box in total?\n\n```css\n.box {\n  width: 200px;\n  padding: 10px;\n  border: 5px solid black;\n}\n```',
        placeholder: 'A number',
        accept: ['230', '230px'],
        explain:
          '200 content + 10 padding on each side (20) + 5 border on each side (10) = **230px**. With `box-sizing: border-box` the answer would be 200px, with the content squeezed to 170px — which is why that reset is so useful.',
        hint: 'Padding and border apply to both sides.',
      },
    },

    {
      id: 'html-a-05',
      title: 'display: how boxes lay themselves out',
      read: `The \`display\` property decides how an element behaves in the flow.

- **\`block\`** — starts a new line, takes the full available width. Width, height and all margins work. (\`div\`, \`p\`, \`h1\`, \`section\`)
- **\`inline\`** — sits in the text flow. **Width and height are ignored**, and vertical margins have no effect. (\`span\`, \`a\`, \`strong\`, \`em\`)
- **\`inline-block\`** — flows inline, but accepts width, height and all margins. The classic way to make a link look like a button.
- **\`none\`** — removed from the page completely, as if it were deleted. (Compare \`visibility: hidden\`, which leaves the space behind.)
- **\`flex\`** and **\`grid\`** — layout systems; the whole of the next level.

## The one that confuses everyone

Setting \`width\` or \`padding-top\` on an inline element appears to do nothing (or leaks over neighbouring lines). The answer is almost always \`display: inline-block\`.

## Accessibility note

\`display: none\` hides content from screen readers too. For content that should be read aloud but not seen — a label for an icon button — use a "visually hidden" utility class instead.`,
      sample: {
        lang: 'css',
        caption: 'Making a link behave like a button, and a visually-hidden helper',
        code: `/* inline by default: the padding here would overlap other lines */
a.plain {
  padding: 12px 20px;
}

/* inline-block: flows in text, but respects the box */
a.button {
  display: inline-block;
  padding: 12px 20px;
  background: #2563eb;
  color: white;
  border-radius: 8px;
  text-decoration: none;
}

.hidden { display: none; }
.invisible { visibility: hidden; }  /* still takes up space */

/* readable by screen readers, invisible on screen */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip-path: inset(50%);
  white-space: nowrap;
}`,
        output: `a.plain  -> padding overlaps the lines above and below
a.button -> a proper blue rounded button that sits in the sentence
.hidden  -> gone, no space
.invisible -> blank gap the same size as the element`,
      },
      question: {
        kind: 'mcq',
        prompt: 'You set `width: 200px` on a `<span>` and nothing changes. Why?',
        options: [
          'Spans cannot be styled',
          '`<span>` is `display: inline`, and inline elements ignore width and height',
          'You need `!important`',
          'The width must be a percentage',
        ],
        answer: 1,
        explain:
          'Inline boxes are sized by their content. Add `display: inline-block` (keeps it in the text flow) or `display: block` (starts a new line) and the width takes effect.',
        hint: 'What is a span’s default display value?',
      },
    },

    {
      id: 'html-a-06',
      title: 'Semantic layout elements',
      read: `You could build any page from \`<div>\`s. You should not. HTML5 gives elements that say what a region *is*, and browsers, screen readers and search engines all use that information.

- \`<header>\` — introductory content for the page or a section
- \`<nav>\` — a block of navigation links
- \`<main>\` — the main content. **One per page**, and it must not be inside header, nav, aside or footer.
- \`<article>\` — a self-contained piece that would still make sense republished alone: a blog post, a product card, a comment
- \`<section>\` — a thematic grouping, which **should have a heading**
- \`<aside>\` — tangentially related content: a sidebar, a pull quote
- \`<footer>\` — closing content for the page or a section
- \`<figure>\` / \`<figcaption>\` — an image, diagram or code block with a caption

## article vs section

Ask: *would this make sense on its own, out of context?* Yes → \`<article>\`. It is a chunk of a larger whole → \`<section>\`. Neither fits and you just need a box → \`<div>\`. That is what divs are for, and using one is not a failure.

## Why it pays off

A screen-reader user can jump straight to \`<main>\` — skipping your entire navigation — because you used the right element. That is a real person saved real time.`,
      sample: {
        lang: 'html',
        caption: 'The same page you would otherwise build from twelve divs',
        code: `<body>
  <header>
    <h1>The Daily Loaf</h1>
    <nav aria-label="Main">
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/recipes">Recipes</a></li>
        <li><a href="/about">About</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <article>
      <header>
        <h2>Sourdough for beginners</h2>
        <p><time datetime="2025-03-14">14 March 2025</time></p>
      </header>

      <p>Sourdough is mostly waiting.</p>

      <section>
        <h3>Ingredients</h3>
        <ul>
          <li>500g strong white flour</li>
          <li>350g water</li>
        </ul>
      </section>

      <figure>
        <img src="loaf.jpg" alt="A round sourdough loaf" width="600" height="400">
        <figcaption>The result, after eighteen hours.</figcaption>
      </figure>
    </article>

    <aside>
      <h2>Related</h2>
      <ul><li><a href="/starter">Making a starter</a></li></ul>
    </aside>
  </main>

  <footer>
    <p>&copy; 2025 The Daily Loaf</p>
  </footer>
</body>`,
        output: `A normal-looking page — but a screen reader can now list its landmarks:
  banner, navigation, main, article, complementary, contentinfo
and jump directly to any of them.`,
      },
      question: {
        kind: 'mcq',
        prompt: 'A blog post that would still make sense if republished on another site. Which element?',
        options: ['`<section>`', '`<article>`', '`<div>`', '`<aside>`'],
        answer: 1,
        explain:
          '`<article>` means exactly "self-contained and independently distributable". A `<section>` is a themed part *of* something; an `<aside>` is tangential; a `<div>` says nothing at all.',
        hint: 'Would it make sense on its own, in a feed reader?',
      },
    },

    {
      id: 'html-a-07',
      title: 'Tables (for data, never for layout)',
      read: `A table presents **two-dimensional data**: rows and columns that relate to each other. In 1998 people used tables for page layout; that is long dead, and CSS Grid does it properly.

## The parts

- \`<table>\` wraps it all
- \`<caption>\` — a title, and the first child. Good for accessibility.
- \`<thead>\`, \`<tbody>\`, \`<tfoot>\` — row groups
- \`<tr>\` — a row
- \`<th>\` — a header cell; \`<td>\` — a data cell

## The attribute that matters

\`<th scope="col">\` or \`<th scope="row">\` tells a screen reader which cells a header governs. Without it, a user hearing "£42" has no idea which column it belongs to. Two words of markup make the difference between a usable table and an unusable one.

## Spanning

\`colspan="2"\` and \`rowspan="3"\` merge cells. Use sparingly — complex spans get confusing fast.

## Styling

\`border-collapse: collapse\` merges double borders into one. Wrap wide tables in a scrolling container so they survive a phone screen.`,
      sample: {
        lang: 'html',
        caption: 'An accessible data table with scoped headers',
        code: `<table>
  <caption>Monthly sales, Q1 2025</caption>
  <thead>
    <tr>
      <th scope="col">Month</th>
      <th scope="col">Units</th>
      <th scope="col">Revenue</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">January</th>
      <td>120</td>
      <td>£2,400</td>
    </tr>
    <tr>
      <th scope="row">February</th>
      <td>150</td>
      <td>£3,000</td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <th scope="row">Total</th>
      <td>270</td>
      <td>£5,400</td>
    </tr>
  </tfoot>
</table>

<style>
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
  thead th { background: #f4f4f4; }
  tbody tr:nth-child(even) { background: #fafafa; }
  caption { text-align: left; font-weight: bold; margin-bottom: 8px; }
</style>`,
        output: `Monthly sales, Q1 2025
┌──────────┬───────┬─────────┐
│ Month    │ Units │ Revenue │
├──────────┼───────┼─────────┤
│ January  │ 120   │ £2,400  │
│ February │ 150   │ £3,000  │
├──────────┼───────┼─────────┤
│ Total    │ 270   │ £5,400  │
└──────────┴───────┴─────────┘`,
      },
      question: {
        kind: 'fill',
        prompt:
          'Which attribute on a `<th>` tells assistive technology whether that header applies to a column or a row?',
        placeholder: 'One word',
        accept: ['scope', 'scope=', 'scope attribute'],
        explain:
          '`scope="col"` or `scope="row"`. Without it a screen reader cannot associate a value with its header, so a table that looks clear on screen becomes meaningless when read aloud.',
        hint: 'It "scopes" the header to a direction.',
      },
    },

    {
      id: 'html-a-08',
      title: 'Forms, part 1: the essentials',
      read: `A form collects input.

\`\`\`html
<form action="/signup" method="post">
  <label for="email">Email</label>
  <input type="email" id="email" name="email" required>
  <button type="submit">Sign up</button>
</form>
\`\`\`

## The pieces

- \`action\` — where the data is sent. \`method="post"\` for anything that changes data or contains a password; \`get\` puts values in the URL, fine for a search box.
- \`name\` — **essential**. It is the key the data arrives under on the server. No \`name\`, no data, no error message.
- \`id\` — links the input to its label.

## Labels are not optional

\`<label for="email">\` must match \`id="email"\` exactly. Then:

- screen readers announce the label when the field is focused
- **clicking the label focuses the field**, which makes checkboxes and radios far easier to hit on a phone

A placeholder is **not** a label: it disappears as soon as typing starts, and grey-on-white placeholder text usually fails contrast requirements.

## Buttons

\`<button type="submit">\` submits, \`type="button"\` does nothing on its own (for JavaScript), \`type="reset"\` clears the form — and almost always annoys people. **A button with no \`type\` inside a form defaults to submit**, which surprises a lot of people.`,
      sample: {
        lang: 'html',
        caption: 'A minimal, correct, accessible form',
        code: `<form action="/signup" method="post">
  <div class="field">
    <label for="name">Full name</label>
    <input type="text" id="name" name="name" autocomplete="name" required>
  </div>

  <div class="field">
    <label for="email">Email address</label>
    <input type="email" id="email" name="email"
           autocomplete="email" placeholder="you@example.com" required>
    <small id="email-help">We will never share it.</small>
  </div>

  <div class="field">
    <label for="password">Password</label>
    <input type="password" id="password" name="password"
           autocomplete="new-password" minlength="8" required>
  </div>

  <button type="submit">Create account</button>
</form>`,
        output: `Full name      [_______________]
Email address  [you@example.com]
               We will never share it.
Password       [_______________]
               [ Create account ]

Clicking "Email address" puts the cursor in the field.`,
      },
      question: {
        kind: 'mcq',
        prompt: 'You submit a form and one field never arrives at the server. What is the most likely cause?',
        options: [
          'It is missing an `id`',
          'It is missing a `name` attribute',
          'It is missing a `<label>`',
          'The method should be `get`',
        ],
        answer: 1,
        explain:
          '`name` is the key under which a value is submitted; without it the browser simply leaves the field out — silently, with no error. `id` is for labels and CSS, and a missing label hurts accessibility but does not affect what is sent.',
        hint: 'Which attribute does the server actually see?',
      },
    },

    {
      id: 'html-a-09',
      title: 'Forms, part 2: input types and validation',
      read: `## Use the right \`type\`

It changes the on-screen keyboard on phones, enables free validation, and often gives you a native picker.

\`text\`, \`email\`, \`password\`, \`number\`, \`tel\`, \`url\`, \`search\`, \`date\`, \`time\`, \`color\`, \`range\`, \`file\`, \`checkbox\`, \`radio\`, \`hidden\`.

\`type="email"\` on a phone puts \`@\` on the keyboard. That is a real usability win for one word of markup.

## Other controls

- \`<select>\` with \`<option>\` — a dropdown; \`<optgroup>\` groups them
- \`<textarea rows="5">\` — multi-line. Note it has a closing tag and no \`value\` attribute.
- \`<fieldset>\` + \`<legend>\` — groups related controls, essential for radio buttons

## Radios and checkboxes

Radio buttons in a group **must share the same \`name\`** — that is what makes them mutually exclusive. Each needs its own \`id\` and \`value\`. Checkboxes are independent, and only send a value when ticked.

## Built-in validation

\`required\`, \`minlength\`, \`maxlength\`, \`min\`, \`max\`, \`step\`, \`pattern="[0-9]{5}"\`. The browser blocks submission and shows a message, for free.

> This is convenience, not security. Anyone can bypass it. **Always validate on the server too.**`,
      sample: {
        lang: 'html',
        caption: 'The full control set, correctly grouped',
        code: `<form action="/order" method="post">
  <fieldset>
    <legend>Delivery speed</legend>
    <label><input type="radio" name="speed" value="standard" checked> Standard</label>
    <label><input type="radio" name="speed" value="express"> Express (+£5)</label>
  </fieldset>

  <label for="qty">Quantity</label>
  <input type="number" id="qty" name="qty" min="1" max="10" value="1" required>

  <label for="when">Delivery date</label>
  <input type="date" id="when" name="when" min="2025-01-01">

  <label for="postcode">Postcode</label>
  <input type="text" id="postcode" name="postcode"
         pattern="[A-Za-z]{1,2}[0-9]{1,2} ?[0-9][A-Za-z]{2}"
         title="e.g. LS1 1AA" required>

  <label for="size">Size</label>
  <select id="size" name="size">
    <optgroup label="Adult">
      <option value="m">Medium</option>
      <option value="l" selected>Large</option>
    </optgroup>
    <optgroup label="Child">
      <option value="s">Small</option>
    </optgroup>
  </select>

  <label for="notes">Delivery notes</label>
  <textarea id="notes" name="notes" rows="4" maxlength="200"></textarea>

  <label><input type="checkbox" name="gift" value="yes"> Gift wrap this order</label>

  <button type="submit">Place order</button>
</form>`,
        output: `Delivery speed
  (•) Standard   ( ) Express (+£5)
Quantity      [1] (spinner, 1–10)
Delivery date [ 2025-06-01 ] (native date picker)
Postcode      [_________] rejects "hello" on submit
Size          [ Large  v ] grouped Adult / Child
Delivery notes[           ] 4 rows, 200 char limit
[x] Gift wrap this order
[ Place order ]`,
      },
      question: {
        kind: 'mcq',
        prompt: 'Three radio buttons let the user pick one delivery speed. What makes them mutually exclusive?',
        options: [
          'They all share the same `name`',
          'They all share the same `id`',
          'They are inside a `<fieldset>`',
          'The `exclusive` attribute',
        ],
        answer: 0,
        explain:
          'A shared `name` defines the group, and a group allows one selection. `id` must be unique on every one of them, and `<fieldset>` is for labelling and layout — helpful, but not what creates the exclusivity.',
        hint: 'Which attribute do all three share — and which must differ?',
      },
    },

    {
      id: 'html-a-10',
      title: 'Paths, files and folders',
      read: `Half of all "it works on my machine" problems are path problems.

## Relative paths

Relative to the **file doing the linking**:

- \`about.html\` — same folder
- \`pages/about.html\` — into the \`pages\` subfolder
- \`../index.html\` — up one folder, then \`index.html\`
- \`../../assets/logo.svg\` — up two, then down into \`assets\`

## Root-relative paths

Starting with \`/\` means "from the site root": \`/images/logo.png\` works identically from any page at any depth. This is what you want once a site has more than one folder — but it does **not** work when opening files directly with \`file://\`, only over a server.

## index.html is special

A server asked for \`/about/\` serves \`/about/index.html\` automatically. That is how you get clean URLs with no \`.html\` on the end.

## Run a local server

\`\`\`
python -m http.server 8000
\`\`\`

Then open \`http://localhost:8000\`. Root-relative paths work, and so do the things a \`file://\` page is not allowed to do (fetch, modules, service workers). It is one command; get in the habit.`,
      sample: {
        lang: 'html',
        caption: 'Site layout, and what each page must write to reach shared assets',
        code: `<!--
site/
  index.html
  styles/main.css
  images/logo.png
  blog/
    index.html
    first-post.html
-->

<!-- in site/index.html -->
<link rel="stylesheet" href="styles/main.css">
<img src="images/logo.png" alt="Logo">
<a href="blog/index.html">Blog</a>

<!-- in site/blog/first-post.html -->
<link rel="stylesheet" href="../styles/main.css">
<img src="../images/logo.png" alt="Logo">
<a href="../index.html">Home</a>
<a href="index.html">All posts</a>

<!-- root-relative: identical in every file, but needs a server -->
<link rel="stylesheet" href="/styles/main.css">
<img src="/images/logo.png" alt="Logo">`,
        output: `$ python -m http.server 8000
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
"GET /blog/first-post.html HTTP/1.1" 200
"GET /styles/main.css HTTP/1.1" 200`,
      },
      question: {
        kind: 'fill',
        prompt:
          'From `site/blog/first-post.html`, what relative path reaches `site/images/logo.png`?',
        placeholder: 'A path',
        accept: ['../images/logo.png', './../images/logo.png'],
        caseSensitive: false,
        explain:
          '`..` climbs from `blog/` up to `site/`, then `images/logo.png` goes back down. Count the folders between the two files and you can always work the path out.',
        hint: 'You need to go up one level first.',
      },
    },

    {
      id: 'html-a-11',
      title: 'The head: metadata that matters',
      read: `Nothing in \`<head>\` is visible, and most of it matters anyway.

## Always

\`\`\`html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Specific page title — Site name</title>
<meta name="description" content="One or two sentences, 150-160 characters.">
\`\`\`

The \`<title>\` and \`description\` are what Google shows in results. Write them for a human deciding whether to click.

## Icons

\`\`\`html
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
\`\`\`

## Social previews (Open Graph)

Without these, a link pasted into a chat app looks like a bare URL. With them you get a card with a title, description and image:

\`\`\`html
<meta property="og:title" content="...">
<meta property="og:description" content="...">
<meta property="og:image" content="https://example.com/preview.png">
<meta property="og:url" content="https://example.com/page">
\`\`\`

\`og:image\` must be an **absolute** URL.

## Also worth knowing

- \`<link rel="canonical">\` — the preferred URL when a page is reachable several ways
- \`<meta name="theme-color">\` — tints the browser UI on mobile
- \`<link rel="preconnect">\` — start the handshake to a font or API host early`,
      sample: {
        lang: 'html',
        caption: 'A production-quality head section',
        code: `<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>Sourdough for beginners — The Daily Loaf</title>
  <meta name="description"
        content="A slow, forgiving sourdough recipe for absolute beginners.
                 Four ingredients, eighteen hours, no special equipment.">

  <link rel="canonical" href="https://dailyloaf.example/sourdough">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <meta name="theme-color" content="#b45309">

  <meta property="og:type" content="article">
  <meta property="og:title" content="Sourdough for beginners">
  <meta property="og:description" content="Four ingredients, eighteen hours.">
  <meta property="og:image" content="https://dailyloaf.example/og/sourdough.png">
  <meta property="og:url" content="https://dailyloaf.example/sourdough">
  <meta name="twitter:card" content="summary_large_image">

  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="/styles/main.css">
</head>`,
        output: `Google result:
  Sourdough for beginners — The Daily Loaf
  dailyloaf.example › sourdough
  A slow, forgiving sourdough recipe for absolute beginners...

Pasted into a chat app:
  [preview image]
  Sourdough for beginners
  Four ingredients, eighteen hours.`,
      },
      question: {
        kind: 'mcq',
        prompt: 'Why must `og:image` be an absolute URL rather than `/og/preview.png`?',
        options: [
          'Relative paths are invalid in meta tags',
          'The service fetching it (a chat app, a social network) is on a different host and has no base to resolve a relative path against',
          'Absolute URLs load faster',
          'It is only a convention',
        ],
        answer: 1,
        explain:
          'Open Graph data is read by a server somewhere else, which sees only the markup text. A relative path has no meaning outside your own origin, so the preview image simply fails to load.',
        hint: 'Who is reading that tag, and where are they?',
      },
    },

    {
      id: 'html-a-12',
      title: 'Project: a styled landing page',
      read: `Everything from this level in one page: semantic structure, an external stylesheet, a form, and a design that holds together.

The build order — follow it and the page comes out right the first time:

1. **Write the HTML first, with no styling at all.** If it reads sensibly top to bottom in plain black text, the structure is sound.
2. Add the reset (\`box-sizing: border-box\`, \`margin: 0\` on body).
3. Set the typographic base on \`body\`: font stack, \`line-height: 1.6\`, colour, a \`max-width\`.
4. Define colours once as custom properties on \`:root\`.
5. Style components (\`.card\`, \`.button\`, \`.field\`) with classes.
6. Check it on a narrow window, then run *validator.w3.org*.

Notice the sample has no \`<div>\` doing a job that a semantic element could do, every form control has a real \`<label>\`, and the colours are defined in exactly one place.`,
      sample: {
        lang: 'html',
        caption: 'Semantic HTML, a small stylesheet, a working form',
        code: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fern — plant care reminders</title>
  <meta name="description" content="Simple watering reminders for people who keep killing their plants.">
  <style>
    *, *::before, *::after { box-sizing: border-box; }

    :root {
      --ink: hsl(150 20% 15%);
      --muted: hsl(150 8% 42%);
      --brand: hsl(150 45% 35%);
      --surface: hsl(150 25% 97%);
      --radius: 12px;
    }

    body {
      margin: 0;
      font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
      line-height: 1.6;
      color: var(--ink);
      background: var(--surface);
    }

    .wrap { max-width: 60rem; margin: 0 auto; padding: 0 1.25rem; }

    header { background: white; border-bottom: 1px solid hsl(150 15% 90%); }
    header .wrap { display: flex; justify-content: space-between;
                   align-items: center; padding-block: 1rem; }
    nav ul { list-style: none; display: flex; gap: 1.5rem; margin: 0; padding: 0; }
    nav a { color: var(--muted); text-decoration: none; }
    nav a:hover { color: var(--brand); }

    .hero { text-align: center; padding-block: 4rem 3rem; }
    .hero h1 { font-size: clamp(2rem, 5vw, 3rem); line-height: 1.15; margin: 0 0 1rem; }
    .hero p { color: var(--muted); font-size: 1.15rem; max-width: 40ch; margin: 0 auto 2rem; }

    .button {
      display: inline-block;
      background: var(--brand);
      color: white;
      padding: 0.85rem 1.75rem;
      border: none;
      border-radius: var(--radius);
      font-size: 1rem;
      text-decoration: none;
      cursor: pointer;
    }
    .button:hover { background: hsl(150 45% 28%); }

    .card {
      background: white;
      border-radius: var(--radius);
      padding: 1.5rem;
      margin-bottom: 1rem;
      box-shadow: 0 1px 3px rgb(0 0 0 / 8%);
    }
    .card h3 { margin-top: 0; }

    .field { margin-bottom: 1rem; }
    .field label { display: block; font-weight: 600; margin-bottom: 0.35rem; }
    .field input {
      width: 100%;
      padding: 0.7rem 0.85rem;
      border: 1px solid hsl(150 15% 80%);
      border-radius: 8px;
      font-size: 1rem;
    }
    .field input:focus { outline: 2px solid var(--brand); outline-offset: 1px; }

    footer { color: var(--muted); font-size: 0.9rem; padding-block: 2rem; text-align: center; }
  </style>
</head>
<body>
  <header>
    <div class="wrap">
      <strong>Fern</strong>
      <nav aria-label="Main">
        <ul>
          <li><a href="#features">Features</a></li>
          <li><a href="#signup">Sign up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <main class="wrap">
    <section class="hero">
      <h1>Stop killing your plants</h1>
      <p>Fern sends you one reminder, on the day each plant actually needs water.</p>
      <a class="button" href="#signup">Get early access</a>
    </section>

    <section id="features">
      <h2>What it does</h2>
      <article class="card">
        <h3>One reminder, not ten</h3>
        <p>No streaks, no badges, no guilt. Just a nudge on the right day.</p>
      </article>
      <article class="card">
        <h3>Knows your plants</h3>
        <p>Pick from 400 species and it works out the schedule for you.</p>
      </article>
    </section>

    <section id="signup">
      <h2>Join the waiting list</h2>
      <form action="/subscribe" method="post" class="card">
        <div class="field">
          <label for="name">Your name</label>
          <input type="text" id="name" name="name" autocomplete="name" required>
        </div>
        <div class="field">
          <label for="email">Email address</label>
          <input type="email" id="email" name="email" autocomplete="email" required>
        </div>
        <button class="button" type="submit">Join the list</button>
      </form>
    </section>
  </main>

  <footer class="wrap">
    <p>&copy; 2025 Fern. Made while learning HTML.</p>
  </footer>
</body>
</html>`,
        output: `A clean green-and-white landing page: sticky-feeling header with nav,
big centred headline and call-to-action button, two feature cards,
and a signup form with proper labels and a visible focus ring.`,
      },
      question: {
        kind: 'mcq',
        prompt:
          'Why write and check the HTML with no CSS at all before styling anything?',
        options: [
          'CSS cannot be added later',
          'Unstyled HTML reveals whether the structure and reading order make sense on their own — which is exactly what screen readers and search engines get',
          'It makes the page load faster',
          'The validator only works on unstyled pages',
        ],
        answer: 1,
        explain:
          'CSS can make a badly structured page *look* fine, hiding problems from you but not from a screen reader, a search engine, or the browser reader mode. If the plain black-and-white version reads correctly top to bottom, the foundation is sound and styling is decoration on top of it.',
        hint: 'What does a screen reader actually receive?',
      },
    },
  ],
}

export default level
